services:
  pg-carOptDB:
    image: postgres:16
    container_name: pg_carOptDB
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: hassan
      POSTGRES_DB: caroptDB
    ports:
      - "5434:5432"
    volumes:
      - ./data/pg_carOptDB:/var/lib/postgresql/data
      - ./docker/pg_carOptDB/initCarOptDB.sql:/docker-entrypoint-initdb.d/init.sql